### ISSUE TITLE
[Request] Cleaning up my old CSS junk 

### ISSUE THREAD

**Issue by translucentleaf** [OakvilleTSA/OakvilleTSA.github.io#10]
So since I've been learning and using CSS grid to start setting up the website layout, I've realized that there's a bunch of old CSS what none of us are really using. 

So right now for my branch I'm going to create a new alternate CSS file and then once you two figure out which CSS is yours I can start combining the two and get rid of anything uneeded.

Also please do not open the alternate index.html on my branch because it's just a bunch of color borders that I'm trying to figure out here. The good news is that I should be able to add content in, although I have to stick with a mobile first approach. So what do you two recommend for the mobile view since we have to have navigation _somewhere_.

**Comment by animus-v0x** [comment]
This should work just fine, I am however we fully break away from Bootstrap because that is what is currently working for anything in our CSS. Move forward with this and we will help along the way.

**Comment by Imnooby** [comment]
Close for now, may need to reopen this some time because it's still a mess, but a different mess
