### ISSUE TITLE
Navbar collapses on itself when the window is shrunk

### ISSUE THREAD

**Issue by Imnooby** [OakvilleTSA/OakvilleTSA.github.io#7]
[Example](https://puu.sh/yZo3C/8ef36875bc.png)

**Comment by animus-v0x** [comment]
Device and display scaling should do the trick, but I don't know exactly how we can make this adapt and I think for the most part this has to be normal :\

**Comment by animus-v0x** [comment]
Fixed in mdl-rewrite: 3e903be5b230b3ed8aaf553b7f3e5f6224c1b771

This one was very broke but works
